---
title: "CV"
---
##Education
\
  


#### PhD Plant Pathology GPA: 4.00/4.00
University of Florida, anticipated Spring 2020  
Major Advisor: [Karen Garrett](http://www.garrettlab.com)  
Dissertation topic: Network modeling of epidemics and information dissemination in formal and informal seed networks  
\  
  
  
#### M.S. Plant Pathology GPA: 3.94/4.00 
The Ohio State University, Columbus, OH, September 2011- December 2013 
Thesis Title: Influence of rainfall patterns on the development of Fusarium head blight, accumulation of deoxynivalenol, and fungicide efficacy.  
\  

  
#### B.A. Biology (Honors in Biology) GPA: 3.46/4.00 
Lafayette College, Easton, PA, Fall 2007- Spring 2011 
Minor: Health Care and Society 
Honors Thesis: Relative disease susceptibility of cultivated varieties of potato to different isolates of Phytophthora infestans.  
\
\
  

##Employment

#### University of Florida · Gainesville, FL September 2016-present
Graduate Research Associate- Department of Plant Pathology, Institute for Sustainable Food Systems, Emerging Pathogens Institute    
\  
  

#### Monsanto Company · St. Louis, MO July 2016-September 2016  
Epidemiology and Portfolio Lead- North America Breeding Plant Health Team  
\  

#### Monsanto Company · St. Louis, MO August 2015-July 2016  
Plant Health Project Lead- North America Breeding Plant Health Team  
\   

#### Monsanto Company · St. Louis, MO January 2013-August 2015   
Research Associate- Soybean Breeding  
\  
  
#### The Ohio State University · Columbus, OH Fall 2011-Present  
Graduate Research Associate  
\  
  

#### Lafayette College · Easton, PA Fall 2010-Spring 2011  
Undergraduate Research Assistant  
\  

#### Lafayette College · Easton, PA Summer 2010  
EXCEL Scholar  




